### ISSUE TITLE
Raycast for UI elements such as buttons is inverted

### ISSUE THREAD

**Issue by Chazzvdh** [SignorPipo/wle_pp#3]
### Describe the bug
The controller's raycast is shot the wrong way, this causes that all UI elements cannot be accessed in the normal way. Now you have to turn the controller around to shoot the raycast in the right direction.

### To Reproduce
1. Add a button with the cursor target component to the scene
2. In play mode, point a controller at the button - You cannot interact with the button
3. In play mode, point the bottom of the controller at the button - Now you can interact with the button

### Expected behavior
The ray cast should be shot from the front of the controller.
![image](https://github.com/signorpipo/wle-pp/assets/114153884/d4d445e9-3b13-4a21-a1c9-93634e63441b)

### Current result:
![image](https://github.com/signorpipo/wle-pp/assets/114153884/bee12b80-e527-44bb-ab24-2e54557c4a7f)

**Comment by signorpipo** [comment]
Hi! Are you using the library directly? Or have you started with one of the PP templates? Like the playground one: https://github.com/signorpipo/wle-pplaygrounds

I advise you to start with one of this template since PP require a bit of setup and is not compatible with some of the built in components in WLE, like the input one for the controllers, which lead to this issue. PP has its own input component (called set-hand-local-transform)

If you want you can contact me on discord! The username is signorpipo

**Comment by Chazzvdh** [comment]
> If you want you can contact me on discord! The username is signorpipo

I have added you on discord.

**Comment by Chazzvdh** [comment]
Adding `set-hand-local-transform` to Left/RightCursor seemed to have fixed the issue
